# Configuracion de los contenedores
services:
  frontend:
    image: client:1.0-sgu
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8081
        API_BASEPATH: /api
        API_PROTOCOL: https
    container_name: sgu-frontend
    ports:
      - "3000:443"
    networks:
      - sgu-net
    volumes:
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - database
    
  backend:
    image: server:1.0-sgu
    build:
      context: ./server
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: sgu_jcgr_database
      DB_USER: root
      DB_PASSWORD: root
      SERVER_SSL_ENABLED: true
      SERVER_SSL_KEYSTORE: /etc/letsencrypt/live/localhost/keystore.p12
      SERVER_SSL_KEYSTORE_PASSWORD: changeit
    container_name: sgu-backend
    ports:
      - "8081:8080"
    networks:
      - sgu-net
    volumes:
      - sgu-volume:/var/lib/mysql
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - frontend

  database:
    image: mysql:8.0
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu_jcgr_database
    ports:
      - "3307:3306"
    networks:
      - sgu-net
    volumes:
      - sgu-volume:/var/lib/mysql

# Redes donde se comunican los contenedores - docker network create --driver bridge sgu-net
networks:
  sgu-net:
    external: true

# Volumenes que ocupan los contenedores - docker volume create sgu-volume
volumes:
  sgu-volume:
    external: true
  certbot-conf:
    external: true